name: visloc 
channels:
  - pytorch        
  - defaults
  - xformers       
  - conda-forge    

dependencies:
  - python=3.9           
  - pip>=20.3             
  - cudatoolkit=11.3     
  - pytorch=1.12.1       
  - torchvision=0.13.1   
  - numpy=1.23.1         
  - matplotlib>=3.1.3    
  - pyyaml               
  - pandas               
  - h5py=3.1.0           
  - yacs=0.1.8           
  - omegaconf            
  - joblib=1.0.1         
  - loguru=0.5.3         
  - pytorch-lightning=1.5.10 
  - xformers=0.0.20      

  - pip:
      - opencv-python==4.5.3.56     
      - kornia>=0.6.11              
      - albumentations==1.0.1 --no-binary=imgaug,albumentations 
      - colour-demosaicing==0.2.2
      - imagesize==1.2.0
      - einops==0.3.0
      - triton                    